# Convolution as Matrix Multiplication


## What is the purpose?

Instead of using `for-loops` to perform 2D convolution on images (or any other 2D matrices) we can convert the filter to a `Toeplitz matrix` and image to a vector and do the convolution just by one `matrix multiplication` (and of course some post-processing on the result of this multiplication to get the final result)



## Why do we do that?

There are many efficient matrix multiplication algorithms, so using them we can have an efficient implementation of convolution operation.

## What is in this document?

Mathematical and algorithmic explanation of this process. I will put a naive Python implementation of this algorithm to make it more clear.<br>
Let's start with some definition and basic operation:

## What is a Toeplitz matrix?
Toeplitz matrix is a matrix in which each values along the main diagonal and sub diagonals are constant. Matrix $G$ is an example:

$$\begin{pmatrix}
	2 & -1 & 0 & \cdots & \cdots & \cdots & \cdots & 1\\
	5 & 2 & -1 & 0 & & & & \vdots\\
	-8 & 5 & 2 & -1 & \ddots & & & \vdots\\
	\vdots & -8 & \ddots & \ddots & \ddots & \ddots & & \vdots\\
	\vdots & & \ddots & \ddots & \ddots & \ddots & 0 & \vdots\\
	\vdots & & & \ddots & 5 & 2 & -1 & 0\\
	\vdots & & & & -8 & 5 & 2 & -1\\
	1 & \cdots & \cdots  & \cdots & \cdots & -8 & 5 & 2\\
	\end{pmatrix}$$
    
In a $N \times N$ matrix, its elements are determined by a ($2N -1$) length sequence
	 $$\{t_n | -(N-1) \le n \le (N-1)\}$$

So given a sequence $t_n$ we can create a Toeplitz matrix by following these steps:    
 - put the sequence in the first column of the matrix.
 - shift it and put it in the next column. When shifting, the last element disappears and a new element of the sequence appears. If there is no such an element, put zero in that location.

specifically: $T(m,n)=t_{m-n}$

$$\begin{pmatrix}
	t_0 & t_{-1} & t_{-2} & \cdots & \cdots & \cdots & \cdots & t_{-(N-1)}\\
	t_1 & t_0 & t_{-1} & t_{-2} & & & & \vdots\\
	t_2 & t_1 & t_0 & t_{-1} & \ddots & & & \vdots\\
	\vdots & t_2 & \ddots & \ddots & \ddots & \ddots & & \vdots\\
	\vdots & & \ddots & \ddots & \ddots & \ddots & t_{-2} & \vdots\\
	\vdots & & & \ddots & t_1 & t_0 & t_{-1} & t_{-2}\\
	\vdots & & & & t_2 & t_1 & t_0 & t_{-1}\\
	t_{(N-1)} & \cdots & \cdots  & \cdots & \cdots & t_2 & t_1 & t_0\\
	\end{pmatrix}$$

Be aware that when we are working with sequences that are defined just for $n \ge 0$ values for $t_n$ when $n \le 0$ should be considered as $0$. For example $4 \times 4$ Toeplitz matrix for the sequence $f[n]=[1,2,3]$ will be:

$$\begin{pmatrix}
	1 & 0 & 0 & 0\\
	2 & 1 & 0 & 0\\
	3 & 2 & 1 & 0\\
	0 & 3 & 2 & 1 \\
	\end{pmatrix}$$
    
<a id="doubly_blocked"></a>

## One more definition: Doubly Blocked Toeplitz matrix
In the matrix $A$, all $A_{ij}$ are matrices. If the structure of $A$, with respects to its sub-matrices is Toeplitz, then matrix $A$ is called \textbf{Block-Toeplitz}.

$$\begin{pmatrix}
	A_{11} & A_{12} & \cdots & A_{1N}\\
	A_{21} & A_{22} & \cdots & A_{2N}\\
	\vdots & \vdots & \vdots & \vdots \\
	A_{M1} & A_{M2} & \cdots & A_{MN}\\
	\end{pmatrix}$$

If each individual $A{ij}$ also is a Toeplitz matrix then $A$ is called \textbf{Doubly Blocked Toeplitz}

## Is this Convolution or Cross Correlation?

Most of the time, the word *convolution* in the deep learning literature is used instead of *cross-correlation*, but here I am explaining the process for convolution as is known in the signal processing community. Simply, for convolution we need to flip the filter (kernel) in both vertical and horizontal directions, but for cross-correlation we don't.

The method explained here performs the convolution (not correlation). Because of the way it is implemented here, there is no need to flip the filter, but if you are doing an example by hand and want to compare the results with the implemented method, remember to consider the flipping step in your calculation.

## Step by Step

Let's explain the algorithm step by step using an example. Codes are written in python and the numpy library is used all over the code.

**Note:** Remember that convolution is a commutative operation, so it does not change the output if we switch the inputs for this operation. For simplicity, I will be calling one of the inputs *input* or `I` and the other *filter* or `F`

### Input and Filter
Input matrix that the filter will be convolved with it, is:

$$I =
	\begin{bmatrix}
	1 & 2 & 3 \\
	4 & 5 & 6 \\
	\end{bmatrix}$$

And let the filter be:

$$F =
	\begin{bmatrix}
	10 & 20 \\
	30 & 40 \\
	\end{bmatrix}$$
   

In [33]:
import numpy as np

# input signal
I = np.array([[1, 2, 3], [4, 5, 6]])
print('I: ', I.shape)
print(I)

 # filter
F = np.array([[10, 20], [30, 40]])
print('F: ',F.shape)
print(F)

I:  (2, 3)
[[1 2 3]
 [4 5 6]]
F:  (2, 2)
[[10 20]
 [30 40]]


<a id="output-size"></a>

### Calculate the final output size
If the input signal is $m_1 \times n_1$ and filter is $m_2 \times n_2$ the size of the convolution will be

$$(m_1 + m_2 -1) \times (n_1 + n_2 -1)$$

This is the size of full discrete linear convolution. One might just use some part of the output based on the application. For example in deep learning literature you can use "valid" or "same" as your padding mode. In these case just parts of the full output is used.

Proper zero padding should be done to get the correct output. Zero padding is the next step.  

In [34]:
# number columns and rows of the input
I_row_num, I_col_num = I.shape

# number of columns and rows of the filter
F_row_num, F_col_num = F.shape

#  calculate the output dimensions
output_row_num = I_row_num + F_row_num - 1
output_col_num = I_col_num + F_col_num - 1
print('output dimension:', output_row_num, output_col_num)


output dimension: 3 4


### Zero-pad the filter matrix
The next step is to zero pad the filter to make it the same size as the output. Zeros should be added to the top and right sides of the filter.

<img src="https://github.com/pablordoricaw/conv_as_mm/blob/main/images/3.png?raw=1" alt="Zero padding" title="Zero padded F" width="300"/>

In [35]:
# zero pad the filter
F_zero_padded = np.pad(F, ((0, output_row_num - F_row_num),
                           (0, output_col_num - F_col_num)),
                        'constant', constant_values=0)
print(f"F_zero_padded:\n{F_zero_padded}")

F_zero_padded:
[[10 20  0  0]
 [30 40  0  0]
 [ 0  0  0  0]]


### Toeplitz matrix for each row of the zero-padded filter
For each row of the zero-padded filter `F_zero_padded` create a Toeplitz matrix and store them in a list. Matrix created using the last row goes to the first cell of this list.

<img src="https://github.com/pablordoricaw/conv_as_mm/blob/main/images/4.png?raw=1" alt="Toeplitz matrix for each row of the zero-padded filter" title="Toeplitz matrix for each row of the zero-padded filter" width="500"/>

**Why these matrices have three columns? Why not two or 5? What is the rule here?**
The important point is that the number of columns of these generated Toeplitz matrices should be same as the number of columns of the input (I) matrix.

In the code, I am using `toeplitz()` function from `scipy.linalg library`. One row of the $F$ is passed to this function and the function puts it as the first column of the its output matrix. Then as it is explained before, this vector should be shifted down and be putted in the second column. For this function, in addition to the first column, we need to define the first row, otherwise, the output of the function would be different than what we expect here. The first element of this first row is same as the first element of the first column, and the rest of the elements should be set to zero. (I know that it doesn't make sense :D read it twice and look at the code)

In [36]:
from scipy.linalg import toeplitz

# use each row of the zero-padded F to creat a toeplitz matrix.
#  Number of columns in this matrices are same as numbe of columns of input signal
toeplitz_list = []
for row in F_zero_padded: # iterate from last row to the first row
    c = np.r_[row[0], np.zeros(I_col_num - 1)]
    toeplitz_m = toeplitz(row, c) # this function is in scipy.linalg library
    toeplitz_list.append(toeplitz_m)
toeplitz_list

[array([[10.,  0.,  0.],
        [20., 10.,  0.],
        [ 0., 20., 10.],
        [ 0.,  0., 20.]]),
 array([[30.,  0.,  0.],
        [40., 30.,  0.],
        [ 0., 40., 30.],
        [ 0.,  0., 40.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])]

### Create doubly blocked toeplitz matrix
Now all these small toeplitz matrices should be arranged in a big doubly blocked toepltiz matrix [as described in this section](#doubly_blocked).

In this example $F_0, F_1, F_2$ are corresponding toeplitz matrices for each row of the filter. They should be filled in the doubly blocked toeplitz matrix in this way:

$$doubly \ blocked =
	\begin{bmatrix}
	F_0 & 0 \\
	F_1 & F_0 \\
	F_2 & F_1 \\
	\end{bmatrix}$$
    
Number of columns in this symbolic matrix should be same as the number of rows in the input signal I.\\
	The following code stores the indexes of $F_0, F_1, F_2$ in this format. This will be used to fill out the doubly blocked toepltiz matrix later.

In [37]:
# doubly blocked toeplitz indices:
#  this matrix defines which toeplitz matrix from toeplitz_list goes to which part of the doubly blocked
c = range(1, F_zero_padded.shape[0]+1)
r = np.r_[c[0], np.zeros(I_row_num-1, dtype=int)]
doubly_indices = toeplitz(c, r)
print('doubly indices \n', doubly_indices)

doubly indices 
 [[1 0]
 [2 1]
 [3 2]]


Now let's fill in the doubly blocked toepltiz matrix. Following code does this part:

In [38]:
# create doubly blocked matrix with zero values
toeplitz_shape = toeplitz_list[0].shape # shape of one toeplitz matrix
h = toeplitz_shape[0]*doubly_indices.shape[0]
w = toeplitz_shape[1]*doubly_indices.shape[1]
doubly_blocked_shape = [h, w]
doubly_blocked = np.zeros(doubly_blocked_shape)

# tile toeplitz matrices for each row in the doubly blocked matrix
b_h, b_w = toeplitz_shape # hight and withs of each block
for i in range(doubly_indices.shape[0]):
    for j in range(doubly_indices.shape[1]):
        start_i = i * b_h
        start_j = j * b_w
        end_i = start_i + b_h
        end_j = start_j + b_w
        doubly_blocked[start_i: end_i, start_j:end_j] = toeplitz_list[doubly_indices[i,j]-1]

print('doubly_blocked:\n', doubly_blocked)

doubly_blocked:
 [[10.  0.  0.  0.  0.  0.]
 [20. 10.  0.  0.  0.  0.]
 [ 0. 20. 10.  0.  0.  0.]
 [ 0.  0. 20.  0.  0.  0.]
 [30.  0.  0. 10.  0.  0.]
 [40. 30.  0. 20. 10.  0.]
 [ 0. 40. 30.  0. 20. 10.]
 [ 0.  0. 40.  0.  0. 20.]
 [ 0.  0.  0. 30.  0.  0.]
 [ 0.  0.  0. 40. 30.  0.]
 [ 0.  0.  0.  0. 40. 30.]
 [ 0.  0.  0.  0.  0. 40.]]


For this example the result will be the following matrix. I've colored parts of the matrix that is related to each of the small toeplitz matrices.

<img src="https://github.com/pablordoricaw/conv_as_mm/blob/main/images/6.png?raw=1" alt="doubly blocked toeplitz" title="doubly blocked toeplitz matrix" width="500">

### Convert the input matrix to a vector
Now that the filter has converted to a doubly blocked Toeplitz matrix, we just need to convert the input signal to a vector and multiply them.

All the rows of the input should be transposed to a column vector and stacked on top of each other. The last row goes first!

<img src="https://github.com/pablordoricaw/conv_as_mm/blob/main/images/7.png?raw=1" alt="vectorized input" title="vectorized input" width="400">

The following function does the vectorization. I am sure that there are much simpler ways to do so, but for the purpose of explanation, this function is implemented in this way.

In [39]:
# call the function
vectorized_I = I.flatten()
print('vectorized_I: ', vectorized_I)

vectorized_I:  [1 2 3 4 5 6]


### Multiply doubly blocked toeplitz matrix with vectorized input signal
Do the matrix multiplication between these two matrices. In this example, the doubly blocked Toeplitz matrix is $ 12 \times 6$ and the vectorized input is $6 \times 1$ so the result of the multiplication is $12 \times 1$.

In [40]:
# get result of the convolution by matrix mupltiplication
result_vector = np.matmul(doubly_blocked, vectorized_I)
print('result_vector: ', result_vector)

result_vector:  [ 10.  40.  70.  60.  70. 230. 330. 240. 120. 310. 380. 240.]


### Last step: reshape the result to a matrix form
From section [output_size](#output-size) we know that the output of the convolution should be $(m_1 + m_2 -1) \times (n_1 + n_2 -1)$. First $(n_1 + n_2 -1)$ elements in the output vector form the last row of the final output and the second $(n_1 + n_2 -1)$ elements go to the second-to-last row of the output matrix. Repeat this process to form the final output matrix.

In this example $n_1 = 3$ and $n_2 = 2$, so every 4 element goes to one row of the output matrix.

<img src="https://github.com/pablordoricaw/conv_as_mm/blob/main/images/8.png?raw=1" alt="reshape the output" width="550">

Following function performs this step:

In [41]:
# reshape the raw rsult to desired matrix form
out_shape = (output_row_num, output_col_num)
my_output = np.reshape(result_vector, out_shape)

print('Result of implemented method: \n', my_output)

Result of implemented method: 
 [[ 10.  40.  70.  60.]
 [ 70. 230. 330. 240.]
 [120. 310. 380. 240.]]


### Compare the result with other convolution methods
We can compare the output of this method with `convolve2d()` function from the `scipy` library.

In [42]:
from scipy import signal

lib_output = signal.convolve2d(I, F, "full")
print('Result using signal processing library\n', lib_output)

assert(my_output.all() == lib_output.all())

Result using signal processing library
 [[ 10  40  70  60]
 [ 70 230 330 240]
 [120 310 380 240]]


As you can see the result on the same I and F matrices is same as the result of the implemented method. The parameter "full" is passed to the `signal.convolve2d()` function to get the full convolution results.

### Put everything together

Lets put all the codes in one function and call it with different inputs

In [43]:
def conv_as_mmult(I, F):
    I_row_num, I_col_num = I.shape

    F_row_num, F_col_num = F.shape

    #  calculate the output dimensions
    output_row_num = I_row_num + F_row_num - 1
    output_col_num = I_col_num + F_col_num - 1

    # zero pad the filter
    F_zero_padded = np.pad(F, ((0, output_row_num - F_row_num),
                               (0, output_col_num - F_col_num)),
                                'constant', constant_values=0)

    toeplitz_list = []
    for row in F_zero_padded:
        c = np.zeros(I_col_num)
        c[0] = row[0]
        toeplitz_m = toeplitz(row, c) # this function is in scipy.linalg library
        toeplitz_list.append(toeplitz_m)

    # doubly blocked toeplitz indices:
    # this matrix defines which toeplitz matrix from toeplitz_list goes to which
    # part of the doubly blocked
    c = range(1, F_zero_padded.shape[0] + 1)
    r = np.r_[c[0], np.zeros(I_row_num - 1, dtype=int)]
    doubly_indices = toeplitz(c, r)

    # create doubly blocked matrix with zero values
    toeplitz_shape = toeplitz_list[0].shape # shape of one Toeplitz matrix
    h = toeplitz_shape[0]*doubly_indices.shape[0]
    w = toeplitz_shape[1]*doubly_indices.shape[1]
    doubly_blocked_shape = [h, w]
    doubly_blocked = np.zeros(doubly_blocked_shape)

    # tile toeplitz matrices for each row in the doubly blocked matrix
    b_h, b_w = toeplitz_shape # height and widths of each block
    for i in range(doubly_indices.shape[0]):
        for j in range(doubly_indices.shape[1]):
            start_i = i * b_h
            start_j = j * b_w
            end_i = start_i + b_h
            end_j = start_j + b_w
            doubly_blocked[start_i: end_i, start_j:end_j] = toeplitz_list[doubly_indices[i,j]-1]

    vectorized_I = I.flatten()
    result_vector = np.matmul(doubly_blocked, vectorized_I)
    return np.reshape(result_vector, (output_row_num, output_col_num))

### Test on bigger examples

Now lets test with bigger input and filter matrices and compare out results with results from singla processing function

In [44]:
# test on different examples

# fill I an F with random numbers
I = np.random.randn(10, 13)
F = np.random.randn(30, 70)

my_result = conv_as_mmult(I, F)

lib_result = signal.convolve2d(I, F, mode="full")

assert(my_result.all() == lib_result.all())

# Cross-Correlation as Matrix Multiplication

Since cross-correlation is the same operation as convolution where the only difference is the filtered is flipped.

We can use the `conv_as_mm()` function to compute cross-correlation by performing a horizontal and vertical flip on the filter before passing it on to the function.

In [45]:
# fill I an F with random numbers
# input signal
I = np.array([[1, 2, 3], [4, 5, 6]])
print('I: ', I.shape)
print(I)
print()

 # filter
F = np.array([[10, 20], [30, 40]])
F_flipped = np.flip(F)
print('F_flipped: ', F_flipped.shape)
print(F_flipped)

print()

my_result = conv_as_mmult(I, F_flipped)
print('Result of implemented method: \n', my_result)
print()

lib_result = signal.correlate2d(I, F, mode="full")
print('Result using signal processing library\n', lib_result)

assert(my_result.all() == lib_result.all())

I:  (2, 3)
[[1 2 3]
 [4 5 6]]

F_flipped:  (2, 2)
[[40 30]
 [20 10]]

Result of implemented method: 
 [[ 40. 110. 180.  90.]
 [180. 370. 470. 210.]
 [ 80. 140. 170.  60.]]

Result using signal processing library
 [[ 40 110 180  90]
 [180 370 470 210]
 [ 80 140 170  60]]


  # References

 - The steps explained here are based on Christophoros Nikou's slides on **Filtering in the Frequency Domain (Circulant Matrices and Convolution)** (http://www.cs.uoi.gr/~cnikou/Courses/Digital_Image_Processing/2010-2011/Chapter_04c_Frequency_Filtering_(Circulant_Matrices).ppt)
 - This post on https://dsp.stackexchange.com/questions/35373/convolution-as-a-doubly-block-circulant-matrix-operating-on-a-vector/35376#35376}{dsp.stackexchange also helped in understanding this algorithm.